name = "jueces"
compatibility_date = "2026-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "jueces"
# Reemplaza con el id que imprime: npx wrangler d1 create jueces
database_id = "936d0537-897d-4d76-89f4-93c6dc848a90"
migrations_dir = "migrations"
